MIN_STUDENT_AGE = 15
MAX_STUDENT_AGE = 100

MIN_NAME_LENGTH = 1
MAX_NAME_LENGTH = 100
MIN_EMAIL_LENGTH = 3
MAX_EMAIL_LENGTH = 255
MIN_STUDENT_ID_LENGTH = 3
MAX_STUDENT_ID_LENGTH = 20
MIN_GROUP_NAME_LENGTH = 4
MAX_GROUP_NAME_LENGTH = 20
MIN_SPECIALTY_CODE_LENGTH = 2
MAX_SPECIALTY_CODE_LENGTH = 10

MIN_COURSE_NUMBER = 1
MAX_COURSE_NUMBER = 6

MIN_ADMISSION_YEAR = 1900

DB_POOL_MIN_CONNECTIONS = 1
DB_POOL_MAX_CONNECTIONS = 10

RATE_LIMIT_REQUESTS = 100 
RATE_LIMIT_PERIOD = "1 minute" 
RATE_LIMIT_REQUESTS_CREATE = 20 
RATE_LIMIT_PERIOD_CREATE = "1 minute" 

DEFAULT_PAGE_OFFSET = 0
DEFAULT_PAGE_LIMIT = 20
MAX_PAGE_LIMIT = 100
